/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '7/29/17 1:39 PM' with Gradle 3.0
 *
 * @author root, @date 7/29/17 1:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
